# AI Configuration
ai.provider=openai
openai.provider=openai
openai.apiKey=${OPENAI_API_KEY}
#???? ??
openai.model=gpt-4o-mini

# Logging Configuration
logging.level.com.example=DEBUG
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j=DEBUG
logging.level.root=DEBUG